# Generated by Django 3.1.3 on 2020-11-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idpklienta', models.CharField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(default='', max_length=30)),
                ('nazwisko', models.CharField(default='', max_length=30)),
                ('tel', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('idpracownika', models.CharField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(default='', max_length=30)),
                ('nazwisko', models.CharField(default='', max_length=30)),
                ('stanowisko', models.CharField(default='cos', max_length=30)),
                ('tel', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('adres', models.CharField(default='cos', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zwiarzak',
            fields=[
                ('idzwierzak', models.CharField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(default='tak', max_length=30)),
                ('gatunek', models.CharField(default='pies', max_length=30)),
                ('rasa', models.CharField(default='cos', max_length=30)),
                ('wiek', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('masa', models.DecimalField(decimal_places=2, default=3, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcja',
            fields=[
                ('idadopcji', models.CharField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('idklient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schron.klient')),
                ('idzwierzak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schron.zwiarzak')),
            ],
        ),
    ]
