# Generated by Django 3.1.3 on 2020-11-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(default='', max_length=30)),
                ('nazwisko', models.CharField(default='', max_length=30)),
                ('tel', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(default='', max_length=30)),
                ('nazwisko', models.CharField(default='', max_length=30)),
                ('stanowisko', models.CharField(default='', max_length=30)),
                ('tel', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('adres', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zwiarzak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(default='', max_length=30)),
                ('gatunek', models.CharField(default='', max_length=30)),
                ('rasa', models.CharField(default='', max_length=30)),
                ('wiek', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('waga', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('idklienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schron.klient')),
                ('idzwierz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schron.zwiarzak')),
            ],
        ),
    ]
