# Generated by Django 3.1.3 on 2020-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcja',
            name='idadopcji',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klient',
            name='idpklienta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='idpracownika',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zwiarzak',
            name='idzwierzak',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
